### ISSUE TITLE
RVIZ 2 Unable to see Panda Robot model

### ISSUE THREAD

**Issue by scole02** [moveit/moveit2_tutorials#155]
### Description

Similiar to issue #108. Panda robot appears to load properly according to the logs/console, but the visual model does not appear in RVIZ.
<img width="925" alt="rvis_panda_screenscap" src="https://user-images.githubusercontent.com/50273323/138583539-dc2ef782-dcee-4e4c-b712-ec23ffecf34a.png">

Looking at the logs there is one Error that is displayed upon starting RVIZ:
`[rviz2-1] [ERROR] [1635056199.843327629] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available`

And another Error that is displayed after choosing the MotionPlanning DisplayType as referenced in Step 1 of the [tutorial](http://moveit2_tutorials.picknik.ai/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html).:
`[move_group-4] [ERROR] [1635056172.626867175] [moveit.ros.occupancy_map_monitor]  : No 3D sensor plugin(s) defined for octomap updates`

### Your environment
* ROS Distro: Foxy
* OS Version: e.g. Ubuntu 20.04 WSL2 on WIN11
* Source or Binary build?: Binary MoveIt release, Source moveit2_tutorials
* If binary, which release version?: MoveIt Foxy release
* If source, which git commit or tag? moveit2_tutorials commit 2676a19

### Steps to reproduce

Followed this [tutorial ](http://moveit2_tutorials.picknik.ai/doc/getting_started/getting_started.html)before running the demo with:
`$ ros2 launch moveit2_tutorials demo.launch.py rviz_tutorial:=true`

### Expected behaviour

Panda robot model mesh displays in rviz2 scene, after adding MotionPlanning display type as seen in the [tutorial](http://moveit2_tutorials.picknik.ai/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html).

### Backtrace or Console output

[Console Output](https://gist.github.com/scole02/5f76ccad8e0e47cefe5943a490588d45)

**Comment by vatanaksoytezer** [comment]
> I tried rebuilding the `moveit2_tutorials` repo using colcon as I did before and noticed that there are a bunch of cmake warnings about paths not existing. However all the packages seem to build properly and finish without error. It appears that the panda parts and description are mentioned here, not sure if this part of the problem?

I am pretty sure that's not the problem. It's just a colcon warning after a rebuild. I am guessing this might be a Windows / Rviz issue? Did you try anything other than MoveIt and able to see robots in Rviz?

**Comment by dpiet** [comment]
@vatanaksoytezer I'm also experiencing this issue again with the latest `foxy` branch. I've made sure to purge all moveit released packages and updated my ros-foxy packages and still the same issue. I'm also on WSL2. I'll try other mesh display examples to rule out a GUI issue.

**Comment by vatanaksoytezer** [comment]
> @vatanaksoytezer I'm also experiencing this issue again with the latest `foxy` branch. I've made sure to purge all moveit released packages and updated my ros-foxy packages and still the same issue. I'm also on WSL2. I'll try other mesh display examples to rule out a GUI issue.

Yes, please try to display anything else, to rule out Windows GUI issues. Can you also share your logs so that I can look for errors?

**Comment by dpiet** [comment]
@vatanaksoytezer I am able to see a robot model mesh via:
`ros2 launch dummy_robot_bringup dummy_robot_bringup.launch.py` then opening rviz2 and adding a RobotModel display with /robot_description topic and changing fixed frame to world. So I don't think the problem is related to anything inherent in the WSL2 environment setup.
[Here is a log output](https://gist.github.com/dpiet/80691e790edb1aac56441f88af128399) of the demo launch

**Comment by dpiet** [comment]
Hi @vatanaksoytezer any thoughts on this lingering issue? Can you confirm you can reproduce?

**Comment by vatanaksoytezer** [comment]
Hi @dpiet thanks for the ping. Sorry for the delays, somehow missed this because of all the notifications. I can't reproduce this in any of my environments (release docker, source docker, local (Ubuntu 20.04) release, local source). And I don't have a clue from the log. I'll try to ping some folks to see if they can reproduce / help.

**Comment by rhaschke** [comment]
This seems to be a rviz issue, not a MoveIt issue. Are you able to see any mesh in rviz? Did you try some of the marker tutorials, for example? Which environment do you use? Locale settings?

**Comment by dpiet** [comment]
@rhaschke I had run `ros2 launch dummy_robot_bringup dummy_robot_bringup.launch.py` successfully. This is on updated WSL2 running Ubuntu 20.04. Are you aware of any rviz issues in this environment?

**Comment by vatanaksoytezer** [comment]
@dpiet I suspect the problem might be with the meshes. [dummy_robot](https://github.com/ros2/demos/blob/foxy/dummy_robot/dummy_robot_bringup/launch/single_rrbot.urdf) does not contain any meshes so that doesn't cancel any possiblity. I would suggest trying to spawn a robot with meshes (ie: turtlebot3) and eliminate the possibility. I have tried to control panda recently in Windows WSL and Ubuntu 20.04 using moveit docker images without any issues.

**Comment by rhaschke** [comment]
I have seen several issues reports for WSL2 recently. Maybe they had an update, which broke something? I don't have a WSL2 system at hand for testing.

**Comment by dpiet** [comment]
This seems to be the related reported issue: https://github.com/ros2/rviz/issues/804
I'm not OP, but the fact this can't be reproduced on various build systems and the reported issue, it appears to be a bug with rviz and/or WSL directly.

**Comment by farukomeraydin** [comment]
Hello, I had a similar problem. I am on Ubuntu 22.04, I am using ROS2 Humble. Check here: [(https://github.com/ros-planning/moveit2/issues/1049)]
This should solve your problem.

**Comment by ncbdrck** [comment]
The problem is with WSL, not ROS since WSL uses an older version of OpenGL. 

I found the answer from this
https://answers.ros.org/question/394135/robot-meshes-not-visible-in-rviz-windows11-wsl2/

Follow the steps here to install new driver packages
https://github.com/microsoft/WSL/discussions/6154#discussioncomment-128526

**Comment by sea-bass** [comment]
Thanks @ncbdrck -- will mark as closed
