### ISSUE TITLE
Setup Assistant "Browse" Dialog Box for config name assignment causes crash 

### ISSUE THREAD

**Issue by lcbw** [moveit/moveit2_tutorials#980]
### Description
After stepping through the MoveIt! Setup Assistant, the last page where the package is named has a "Browse" button. Clicking the "Browse" button causes the assistant to freeze and never recover. 

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* Binary Build 
* 2.5.5-1jammy.20241007.235932

### Steps to reproduce
Use the MoveIt! Setup Assistant to create a simple package with one robotic arm, one kinematic chain using RRTConnect and KDL, and on the final page click "Browse" to assist in populating absolute filepath for the desired location of the output files. 

### Expected behaviour
Clicking "Browse" should bring up an interactive file explorer to assist in population of the user's desired filepath for the resultant configuration files. 

### Backtrace or Console output
(Nothing comes up in console)

**Comment by mikeferguson** [comment]
Binaries were quite out of date (more than year since we released to Humble) but have just recently been updated. I believe this particular issue is likely resolved in the new release - please try it out.

And if there are still issues, I recommend opening a ticket on the actual moveit2 repo, rather than tutorials (we have a lot more maintainers over there that are more responsive)
